### ISSUE TITLE
Remove Line Break

### ISSUE THREAD

**Issue by RGTimothy** [letyii/yii2-tinymce#1]
is "convert_newlines_to_brs" option can be implemented?

**Comment by nguago** [comment]
http://www.tinymce.com/wiki.php/Configuration3x:convert_newlines_to_brs

$form->field($model, 'content')->widget(letyii\tinymce\Tinymce::className(), [
    'options' => [
        'class' => 'your_class',
    ],
    'configs' => [
        'convert_newlines_to_brs' => true,
    ],
]);
