### ISSUE TITLE
validation error on first submit

### ISSUE THREAD

**Issue by davidtim** [letyii/yii2-tinymce#5]
Hello,
It's a great extension, but i face an error when i first submit i got validation error. at the second submit everything is ok.

**Comment by nguago** [comment]
can u show error ?

**Comment by davidtim** [comment]
it was just show validation error at the first time i click submit

**Comment by nguago** [comment]
I can not fix if I did not know there was a problem

**Comment by davidtim** [comment]
sorry, i'm new in yii. all i can tell is that when i install your extension and put it in my form like below.
<?= $form->field($model, 'detail['.$key.']')->widget(letyii\tinymce\Tinymce::className(), [
                    'options' => [
                        'class' => 'your_class',
                    ],
                ]);
            ?>
and at the first time i submit it's show error validation, but the second time it's ok

**Comment by nguago** [comment]
but now ok ?
If u get errors, save a image ps! I will fix it !

**Comment by davidtim** [comment]
i mean i have to submit the form twice(first time got error validation, second time success).

**Comment by nguago** [comment]
chat skype with me: nguago
and send me your teamviewer ID
